services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    env_file: 
    - .env.local
    restart: on-failure
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /docker/app/

  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env.local
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: